export default class IColors {
  static readonly color999 = 0xff999999
  static readonly color333 = 0xff333333
  //聊天框文本文字颜色
  static readonly color1R1E20 = 0xff1E1E20
  //群聊用户昵称文字颜色
  static readonly color91939A = 0xff91939A
  static readonly colorOrange = 0xffCB8656
  static readonly color666 = 0xff666666
  static readonly color737D92 = 0xff737D92
  //默认背景颜色
  static readonly colorF3F3F5 = 0xffF3F3F5
  //主要文字浅黄色颜色
  static readonly colorFED8BD = 0xffFED8BD
}