export default class HttpIp {

  //dev
  // static PORT = "https://dev-api.gqj.live/v2/"
  // static origin = "https://dev-ws-android.gqj.live"
  // static ws_address = "wss://dev-ws.gqj.live";
  // static HOST_H5_ANALYST = "https://m.gqj106.com/";
  // static readonly DB_PREFIX = 'dev';
  static readonly APP_PRIVACY = "https://pages.xl1x.com/178_privacy_html.html";
  static readonly APP_PROTOCOL = "https://pages.xl1x.com/178_user_protocol.html";

  //prod
  static PORT = "https://api.gqj.live/v2/"
  static origin = "https://ws-android.gqj.live"
  static ws_address = "wss://ws.gqj.live";
  static HOST_H5_ANALYST = "https://m.gqj106.com/";
  static readonly DB_PREFIX = 'prod';
}