import { UserBean } from './user'

export class FriendKeyData {
  data_key: Array<string> | null
  data: JSON
}


/*{
    A: Array<UserBean> | null
    B: Array<UserBean> | null
    C: Array<UserBean> | null
    D: Array<UserBean> | null
    E: Array<UserBean> | null
    F: Array<UserBean> | null
    I: Array<UserBean> | null
    J: Array<UserBean> | null
    K: Array<UserBean> | null
    L: Array<UserBean> | null
    M: Array<UserBean> | null
    N: Array<UserBean> | null
    O: Array<UserBean> | null
    P: Array<UserBean> | null
    Q: Array<UserBean> | null
    R: Array<UserBean> | null
    S: Array<UserBean> | null
    T: Array<UserBean> | null
    U: Array<UserBean> | null
    V: Array<UserBean> | null
    W: Array<UserBean> | null
    X: Array<UserBean> | null
    Y: Array<UserBean> | null
    Z: Array<UserBean> | null
    #: Array<UserBean> | null
  }*/